-- Disable RLS on all tables so Prisma can read/write
ALTER TABLE "Agency" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Verification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Property" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PropertyImage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Lead" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AnalyticsEvent" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AgencyNotification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PropertyFavorite" DISABLE ROW LEVEL SECURITY;
